services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks: [shipping_network]
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: broker
    networks: [shipping_network]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper

  account-service:
    build:
      context: ./account-service
    image: account-service
    container_name: account-service
    networks: [shipping_network]
    ports:
      - "9000:9000"
    environment:
      - ACCOUNT_STORE_FILE=data/accounts.json
      - ACCOUNT_RESET_STORE=false
    volumes:
      - account-data:/project/data
    restart: always

  delivery-service:
    build:
      context: ./delivery-service
    image: delivery-service
    container_name: delivery-service
    networks: [shipping_network]
    ports:
      - "9002:9002"
      - "9003:9003"
      - "9400:9400"
    depends_on:
      - kafka

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    networks: [shipping_network]
    ports:
      - "8080:8080"
      - "9401:9401"
    environment:
      - ACCOUNT_HOST=account-service
      - DELIVERY_HOST=delivery-service
    depends_on:
      - account-service
      - delivery-service
      - kafka
    healthcheck:
      test: curl --fail http://api-gateway:8080/api/v1/health/live || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "autoheal=true"
    restart: always

  autoheal:
    image: willfarrell/autoheal:1.1.0
    container_name: autoheal
    networks: [shipping_network]
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks: [shipping_network]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - delivery-service
      - api-gateway
    restart: always

networks:
  shipping_network:
    driver: bridge

volumes:
  account-data:
